#!/usr/bin/env python3
"""Generate the questions_normal.json dataset with ~1 000 curated entries."""
from __future__ import annotations

import json
import random
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, List, Sequence

DATA_PATH = Path(__file__).resolve().parents[1] / "data" / "questions_normal.json"
RNG = random.Random(42)


@dataclass(frozen=True)
class Species:
    common: str
    latin: str
    family: str
    category: str
    product: str
    climate: str
    origin: str
    photosynthesis: str
    edible_part: str | None = None


SPECIES_DATA: List[Species] = [
    Species(
        common="Pomme de terre",
        latin="Solanum tuberosum",
        family="Solanaceae",
        category="Tubercule amylacé",
        product="tubercules riches en amidon",
        climate="tempéré frais",
        origin="Andes centrales",
        photosynthesis="C3",
        edible_part="tubercule",
    ),
    Species(
        common="Blé tendre",
        latin="Triticum aestivum",
        family="Poaceae",
        category="Céréale",
        product="grains panifiables",
        climate="tempéré",
        origin="Croissant fertile",
        photosynthesis="C3",
        edible_part="grain",
    ),
    Species(
        common="Riz asiatique",
        latin="Oryza sativa",
        family="Poaceae",
        category="Céréale",
        product="grains décortiqués",
        climate="tropical humide",
        origin="Asie orientale",
        photosynthesis="C3",
        edible_part="grain",
    ),
    Species(
        common="Maïs",
        latin="Zea mays",
        family="Poaceae",
        category="Céréale",
        product="grains riches en amidon",
        climate="tempéré chaud",
        origin="Mexique central",
        photosynthesis="C4",
        edible_part="grain",
    ),
    Species(
        common="Orge",
        latin="Hordeum vulgare",
        family="Poaceae",
        category="Céréale",
        product="grains pour malt",
        climate="tempéré frais",
        origin="Croissant fertile",
        photosynthesis="C3",
        edible_part="grain",
    ),
    Species(
        common="Avoine",
        latin="Avena sativa",
        family="Poaceae",
        category="Céréale",
        product="flocons et fourrage",
        climate="tempéré humide",
        origin="Europe occidentale",
        photosynthesis="C3",
        edible_part="grain",
    ),
    Species(
        common="Seigle",
        latin="Secale cereale",
        family="Poaceae",
        category="Céréale",
        product="grains pour pain noir",
        climate="tempéré froid",
        origin="Asie occidentale",
        photosynthesis="C3",
        edible_part="grain",
    ),
    Species(
        common="Sorgho",
        latin="Sorghum bicolor",
        family="Poaceae",
        category="Céréale",
        product="grains pour bouillies",
        climate="tropical sec",
        origin="Sahel africain",
        photosynthesis="C4",
        edible_part="grain",
    ),
    Species(
        common="Millet perlé",
        latin="Pennisetum glaucum",
        family="Poaceae",
        category="Céréale",
        product="grains pour semoules",
        climate="tropical sec",
        origin="Afrique de l'Ouest",
        photosynthesis="C4",
        edible_part="grain",
    ),
    Species(
        common="Millet commun",
        latin="Panicum miliaceum",
        family="Poaceae",
        category="Céréale",
        product="grains pour bouillies",
        climate="tempéré continental",
        origin="Asie centrale",
        photosynthesis="C4",
        edible_part="grain",
    ),
    Species(
        common="Quinoa",
        latin="Chenopodium quinoa",
        family="Amaranthaceae",
        category="Pseudo-céréale",
        product="graines protéinées",
        climate="andins frais",
        origin="Andes centrales",
        photosynthesis="C3",
        edible_part="grain",
    ),
    Species(
        common="Amarante",
        latin="Amaranthus caudatus",
        family="Amaranthaceae",
        category="Pseudo-céréale",
        product="graines riches en lysine",
        climate="tropical d'altitude",
        origin="Andes péruviennes",
        photosynthesis="C4",
        edible_part="grain",
    ),
    Species(
        common="Manioc",
        latin="Manihot esculenta",
        family="Euphorbiaceae",
        category="Tubercule amylacé",
        product="racines féculentes",
        climate="tropical humide",
        origin="Bassin amazonien",
        photosynthesis="C3",
        edible_part="racine",
    ),
    Species(
        common="Patate douce",
        latin="Ipomoea batatas",
        family="Convolvulaceae",
        category="Tubercule sucré",
        product="tubercules sucrés",
        climate="tropical humide",
        origin="Amérique centrale",
        photosynthesis="C3",
        edible_part="tubercule",
    ),
    Species(
        common="Igname",
        latin="Dioscorea rotundata",
        family="Dioscoreaceae",
        category="Tubercule amylacé",
        product="tubercules riches en amidon",
        climate="tropical humide",
        origin="Afrique de l'Ouest",
        photosynthesis="C3",
        edible_part="tubercule",
    ),
    Species(
        common="Taro",
        latin="Colocasia esculenta",
        family="Araceae",
        category="Tubercule amylacé",
        product="cormes riches en amidon",
        climate="tropical humide",
        origin="Asie du Sud-Est",
        photosynthesis="C3",
        edible_part="corme",
    ),
    Species(
        common="Carotte",
        latin="Daucus carota subsp. sativus",
        family="Apiaceae",
        category="Racine potagère",
        product="racines riches en carotène",
        climate="tempéré",
        origin="Asie centrale",
        photosynthesis="C3",
        edible_part="racine",
    ),
    Species(
        common="Betterave sucrière",
        latin="Beta vulgaris subsp. vulgaris",
        family="Amaranthaceae",
        category="Racine potagère",
        product="racines riches en saccharose",
        climate="tempéré frais",
        origin="Europe méridionale",
        photosynthesis="C3",
        edible_part="racine",
    ),
    Species(
        common="Navet",
        latin="Brassica rapa subsp. rapa",
        family="Brassicaceae",
        category="Racine potagère",
        product="racines charnues",
        climate="tempéré frais",
        origin="Europe orientale",
        photosynthesis="C3",
        edible_part="racine",
    ),
    Species(
        common="Radis",
        latin="Raphanus sativus",
        family="Brassicaceae",
        category="Racine potagère",
        product="racines croquantes",
        climate="tempéré",
        origin="Asie orientale",
        photosynthesis="C3",
        edible_part="racine",
    ),
    Species(
        common="Panais",
        latin="Pastinaca sativa",
        family="Apiaceae",
        category="Racine potagère",
        product="racines sucrées",
        climate="tempéré frais",
        origin="Europe occidentale",
        photosynthesis="C3",
        edible_part="racine",
    ),
    Species(
        common="Oignon",
        latin="Allium cepa",
        family="Amaryllidaceae",
        category="Bulbe condimentaire",
        product="bulbes aromatiques",
        climate="tempéré",
        origin="Asie centrale",
        photosynthesis="C3",
        edible_part="bulbe",
    ),
    Species(
        common="Ail",
        latin="Allium sativum",
        family="Amaryllidaceae",
        category="Bulbe condimentaire",
        product="bulbes aromatiques",
        climate="tempéré",
        origin="Asie centrale",
        photosynthesis="C3",
        edible_part="bulbe",
    ),
    Species(
        common="Échalote",
        latin="Allium cepa Aggregatum Group",
        family="Amaryllidaceae",
        category="Bulbe condimentaire",
        product="bulbes alliacés",
        climate="tempéré",
        origin="Asie centrale",
        photosynthesis="C3",
        edible_part="bulbe",
    ),
    Species(
        common="Poireau",
        latin="Allium porrum",
        family="Amaryllidaceae",
        category="Légume feuille",
        product="fûts et feuilles",
        climate="tempéré frais",
        origin="Méditerranée orientale",
        photosynthesis="C3",
        edible_part="feuille",
    ),
    Species(
        common="Céleri-branche",
        latin="Apium graveolens var. dulce",
        family="Apiaceae",
        category="Légume feuille",
        product="pétiole croquant",
        climate="tempéré humide",
        origin="Méditerranée",
        photosynthesis="C3",
        edible_part="tige",
    ),
    Species(
        common="Céleri-rave",
        latin="Apium graveolens var. rapaceum",
        family="Apiaceae",
        category="Racine potagère",
        product="racines sphériques",
        climate="tempéré",
        origin="Méditerranée",
        photosynthesis="C3",
        edible_part="racine",
    ),
    Species(
        common="Laitue",
        latin="Lactuca sativa",
        family="Asteraceae",
        category="Légume feuille",
        product="feuilles croquantes",
        climate="tempéré frais",
        origin="Méditerranée",
        photosynthesis="C3",
        edible_part="feuille",
    ),
    Species(
        common="Épinard",
        latin="Spinacia oleracea",
        family="Amaranthaceae",
        category="Légume feuille",
        product="feuilles tendres",
        climate="tempéré frais",
        origin="Asie occidentale",
        photosynthesis="C3",
        edible_part="feuille",
    ),
    Species(
        common="Blette",
        latin="Beta vulgaris subsp. cicla",
        family="Amaranthaceae",
        category="Légume feuille",
        product="feuilles et côtes",
        climate="tempéré",
        origin="Méditerranée",
        photosynthesis="C3",
        edible_part="feuille",
    ),
    Species(
        common="Chou pommé",
        latin="Brassica oleracea var. capitata",
        family="Brassicaceae",
        category="Légume feuille",
        product="pomme feuillue",
        climate="tempéré",
        origin="Europe maritime",
        photosynthesis="C3",
        edible_part="feuille",
    ),
    Species(
        common="Chou kale",
        latin="Brassica oleracea var. sabellica",
        family="Brassicaceae",
        category="Légume feuille",
        product="feuilles frisées",
        climate="tempéré frais",
        origin="Europe du Nord",
        photosynthesis="C3",
        edible_part="feuille",
    ),
    Species(
        common="Brocoli",
        latin="Brassica oleracea var. italica",
        family="Brassicaceae",
        category="Légume fleur",
        product="inflorescences immatures",
        climate="tempéré frais",
        origin="Méditerranée",
        photosynthesis="C3",
        edible_part="inflorescence",
    ),
    Species(
        common="Chou-fleur",
        latin="Brassica oleracea var. botrytis",
        family="Brassicaceae",
        category="Légume fleur",
        product="inflorescences compactes",
        climate="tempéré frais",
        origin="Méditerranée",
        photosynthesis="C3",
        edible_part="inflorescence",
    ),
    Species(
        common="Chou de Bruxelles",
        latin="Brassica oleracea var. gemmifera",
        family="Brassicaceae",
        category="Légume feuille",
        product="bourgeons axillaires",
        climate="tempéré frais",
        origin="Belgique",
        photosynthesis="C3",
        edible_part="bourgeon",
    ),
    Species(
        common="Artichaut",
        latin="Cynara cardunculus var. scolymus",
        family="Asteraceae",
        category="Légume fleur",
        product="capitules immatures",
        climate="méditerranéen",
        origin="Bassin méditerranéen",
        photosynthesis="C3",
        edible_part="inflorescence",
    ),
    Species(
        common="Asperge",
        latin="Asparagus officinalis",
        family="Asparagaceae",
        category="Légume tige",
        product="turions tendres",
        climate="tempéré",
        origin="Méditerranée",
        photosynthesis="C3",
        edible_part="tige",
    ),
    Species(
        common="Courgette",
        latin="Cucurbita pepo var. cylindrica",
        family="Cucurbitaceae",
        category="Légume-fruit",
        product="fruits immatures",
        climate="tempéré chaud",
        origin="Mexique",
        photosynthesis="C3",
        edible_part="fruit",
    ),
    Species(
        common="Tomate",
        latin="Solanum lycopersicum",
        family="Solanaceae",
        category="Légume-fruit",
        product="baies juteuses",
        climate="tempéré chaud",
        origin="Andes occidentales",
        photosynthesis="C3",
        edible_part="fruit",
    ),
    Species(
        common="Poivron",
        latin="Capsicum annuum",
        family="Solanaceae",
        category="Légume-fruit",
        product="baies charnues",
        climate="tempéré chaud",
        origin="Mexique",
        photosynthesis="C3",
        edible_part="fruit",
    ),
    Species(
        common="Aubergine",
        latin="Solanum melongena",
        family="Solanaceae",
        category="Légume-fruit",
        product="baies violettes",
        climate="tropical humide",
        origin="Asie du Sud",
        photosynthesis="C3",
        edible_part="fruit",
    ),
    Species(
        common="Concombre",
        latin="Cucumis sativus",
        family="Cucurbitaceae",
        category="Légume-fruit",
        product="baies rafraîchissantes",
        climate="tempéré chaud",
        origin="Inde du Nord",
        photosynthesis="C3",
        edible_part="fruit",
    ),
    Species(
        common="Melon",
        latin="Cucumis melo",
        family="Cucurbitaceae",
        category="Fruit non climactérique",
        product="fruits sucrés",
        climate="tempéré chaud",
        origin="Afrique de l'Est",
        photosynthesis="C3",
        edible_part="fruit",
    ),
    Species(
        common="Pastèque",
        latin="Citrullus lanatus",
        family="Cucurbitaceae",
        category="Fruit non climactérique",
        product="fruits très aqueux",
        climate="tropical sec",
        origin="Afrique australe",
        photosynthesis="C3",
        edible_part="fruit",
    ),
    Species(
        common="Citrouille",
        latin="Cucurbita maxima",
        family="Cucurbitaceae",
        category="Légume-fruit",
        product="baies volumineuses",
        climate="tempéré",
        origin="Andes du Sud",
        photosynthesis="C3",
        edible_part="fruit",
    ),
    Species(
        common="Courge butternut",
        latin="Cucurbita moschata",
        family="Cucurbitaceae",
        category="Légume-fruit",
        product="fruits musqués",
        climate="tropical humide",
        origin="Amérique centrale",
        photosynthesis="C3",
        edible_part="fruit",
    ),
    Species(
        common="Pois",
        latin="Pisum sativum",
        family="Fabaceae",
        category="Légumineuse",
        product="graines vertes",
        climate="tempéré frais",
        origin="Méditerranée orientale",
        photosynthesis="C3",
        edible_part="graine",
    ),
    Species(
        common="Haricot commun",
        latin="Phaseolus vulgaris",
        family="Fabaceae",
        category="Légumineuse",
        product="graines sèches ou fraîches",
        climate="tempéré chaud",
        origin="Amérique centrale",
        photosynthesis="C3",
        edible_part="graine",
    ),
    Species(
        common="Soja",
        latin="Glycine max",
        family="Fabaceae",
        category="Légumineuse oléagineuse",
        product="graines riches en protéines",
        climate="tempéré chaud",
        origin="Chine du Nord",
        photosynthesis="C3",
        edible_part="graine",
    ),
    Species(
        common="Lentille",
        latin="Lens culinaris",
        family="Fabaceae",
        category="Légumineuse",
        product="graines lensiculaires",
        climate="semi-aride",
        origin="Croissant fertile",
        photosynthesis="C3",
        edible_part="graine",
    ),
    Species(
        common="Pois chiche",
        latin="Cicer arietinum",
        family="Fabaceae",
        category="Légumineuse",
        product="graines riches en protéines",
        climate="semi-aride",
        origin="Moyen-Orient",
        photosynthesis="C3",
        edible_part="graine",
    ),
    Species(
        common="Fève",
        latin="Vicia faba",
        family="Fabaceae",
        category="Légumineuse",
        product="graines larges",
        climate="tempéré frais",
        origin="Méditerranée",
        photosynthesis="C3",
        edible_part="graine",
    ),
    Species(
        common="Lupin blanc",
        latin="Lupinus albus",
        family="Fabaceae",
        category="Légumineuse",
        product="graines riches en protéines",
        climate="méditerranéen",
        origin="Bassin méditerranéen",
        photosynthesis="C3",
        edible_part="graine",
    ),
    Species(
        common="Luzerne",
        latin="Medicago sativa",
        family="Fabaceae",
        category="Plante fourragère",
        product="fourrage riche en protéines",
        climate="tempéré",
        origin="Asie occidentale",
        photosynthesis="C3",
        edible_part="feuille",
    ),
    Species(
        common="Arachide",
        latin="Arachis hypogaea",
        family="Fabaceae",
        category="Légumineuse oléagineuse",
        product="graines oléagineuses",
        climate="tropical sec",
        origin="Brésil nord-est",
        photosynthesis="C3",
        edible_part="graine",
    ),
    Species(
        common="Pois d'Angole",
        latin="Cajanus cajan",
        family="Fabaceae",
        category="Légumineuse",
        product="graines protéinées",
        climate="tropical sec",
        origin="Inde péninsulaire",
        photosynthesis="C3",
        edible_part="graine",
    ),
    Species(
        common="Caféier arabica",
        latin="Coffea arabica",
        family="Rubiaceae",
        category="Plante stimulante",
        product="graines torréfiées",
        climate="tropical d'altitude",
        origin="Plateaux éthiopiens",
        photosynthesis="C3",
        edible_part="grain",
    ),
    Species(
        common="Théier",
        latin="Camellia sinensis",
        family="Theaceae",
        category="Plante stimulante",
        product="feuilles pour infusion",
        climate="subtropical humide",
        origin="Chine du Sud",
        photosynthesis="C3",
        edible_part="feuille",
    ),
    Species(
        common="Cacaoyer",
        latin="Theobroma cacao",
        family="Malvaceae",
        category="Plante stimulante",
        product="graines pour cacao",
        climate="tropical humide",
        origin="Forêts amazoniennes",
        photosynthesis="C3",
        edible_part="graine",
    ),
    Species(
        common="Vigne vinifère",
        latin="Vitis vinifera",
        family="Vitaceae",
        category="Fruit climactérique",
        product="baies pour vin",
        climate="tempéré",
        origin="Proche-Orient",
        photosynthesis="C3",
        edible_part="fruit",
    ),
    Species(
        common="Pommier",
        latin="Malus domestica",
        family="Rosaceae",
        category="Arbre fruitier tempéré",
        product="fruits à pépins",
        climate="tempéré",
        origin="Asie centrale",
        photosynthesis="C3",
        edible_part="fruit",
    ),
    Species(
        common="Poirier",
        latin="Pyrus communis",
        family="Rosaceae",
        category="Arbre fruitier tempéré",
        product="fruits à pépins",
        climate="tempéré",
        origin="Europe occidentale",
        photosynthesis="C3",
        edible_part="fruit",
    ),
    Species(
        common="Pêcher",
        latin="Prunus persica",
        family="Rosaceae",
        category="Arbre fruitier tempéré",
        product="drupes juteuses",
        climate="tempéré chaud",
        origin="Chine du Nord",
        photosynthesis="C3",
        edible_part="fruit",
    ),
    Species(
        common="Abricotier",
        latin="Prunus armeniaca",
        family="Rosaceae",
        category="Arbre fruitier tempéré",
        product="drupes sucrées",
        climate="tempéré sec",
        origin="Asie centrale",
        photosynthesis="C3",
        edible_part="fruit",
    ),
    Species(
        common="Cerisier doux",
        latin="Prunus avium",
        family="Rosaceae",
        category="Arbre fruitier tempéré",
        product="drupes rouges",
        climate="tempéré",
        origin="Europe orientale",
        photosynthesis="C3",
        edible_part="fruit",
    ),
    Species(
        common="Prunier d'Europe",
        latin="Prunus domestica",
        family="Rosaceae",
        category="Arbre fruitier tempéré",
        product="drupes violettes",
        climate="tempéré",
        origin="Caucase",
        photosynthesis="C3",
        edible_part="fruit",
    ),
    Species(
        common="Olivier",
        latin="Olea europaea",
        family="Oleaceae",
        category="Arbre fruitier méditerranéen",
        product="drupes oléagineuses",
        climate="méditerranéen",
        origin="Méditerranée orientale",
        photosynthesis="C3",
        edible_part="fruit",
    ),
    Species(
        common="Cocotier",
        latin="Cocos nucifera",
        family="Arecaceae",
        category="Palmier cultivé",
        product="noix riches en huile",
        climate="tropical côtier",
        origin="Asie du Sud-Est",
        photosynthesis="C3",
        edible_part="fruit",
    ),
    Species(
        common="Palmier à huile",
        latin="Elaeis guineensis",
        family="Arecaceae",
        category="Palmier cultivé",
        product="huile de palme",
        climate="tropical humide",
        origin="Afrique de l'Ouest",
        photosynthesis="C3",
        edible_part="fruit",
    ),
    Species(
        common="Banane dessert",
        latin="Musa acuminata",
        family="Musaceae",
        category="Fruit climactérique",
        product="baies sucrées",
        climate="tropical humide",
        origin="Asie du Sud-Est",
        photosynthesis="C3",
        edible_part="fruit",
    ),
    Species(
        common="Banane plantain",
        latin="Musa × paradisiaca",
        family="Musaceae",
        category="Fruit féculent",
        product="fruits riches en amidon",
        climate="tropical humide",
        origin="Asie du Sud-Est",
        photosynthesis="C3",
        edible_part="fruit",
    ),
    Species(
        common="Ananas",
        latin="Ananas comosus",
        family="Bromeliaceae",
        category="Fruit tropical",
        product="infrutescences sucrées",
        climate="tropical",
        origin="Plateaux brésiliens",
        photosynthesis="CAM",
        edible_part="fruit",
    ),
    Species(
        common="Mangier",
        latin="Mangifera indica",
        family="Anacardiaceae",
        category="Fruit tropical",
        product="drupes sucrées",
        climate="tropical humide",
        origin="Inde orientale",
        photosynthesis="C3",
        edible_part="fruit",
    ),
    Species(
        common="Papayer",
        latin="Carica papaya",
        family="Caricaceae",
        category="Fruit tropical",
        product="baies allongées",
        climate="tropical",
        origin="Amérique centrale",
        photosynthesis="C3",
        edible_part="fruit",
    ),
    Species(
        common="Goyavier",
        latin="Psidium guajava",
        family="Myrtaceae",
        category="Fruit tropical",
        product="baies aromatiques",
        climate="tropical",
        origin="Amérique tropicale",
        photosynthesis="C3",
        edible_part="fruit",
    ),
    Species(
        common="Avocatier",
        latin="Persea americana",
        family="Lauraceae",
        category="Fruit oléagineux",
        product="drupes riches en lipides",
        climate="tropical d'altitude",
        origin="Mexique central",
        photosynthesis="C3",
        edible_part="fruit",
    ),
    Species(
        common="Oranger doux",
        latin="Citrus × sinensis",
        family="Rutaceae",
        category="Agrume",
        product="hespérides sucrées",
        climate="subtropical",
        origin="Chine méridionale",
        photosynthesis="C3",
        edible_part="fruit",
    ),
    Species(
        common="Citronnier",
        latin="Citrus limon",
        family="Rutaceae",
        category="Agrume",
        product="hespérides acides",
        climate="méditerranéen",
        origin="Méditerranée orientale",
        photosynthesis="C3",
        edible_part="fruit",
    ),
    Species(
        common="Pamplemoussier",
        latin="Citrus × paradisi",
        family="Rutaceae",
        category="Agrume",
        product="hespérides amères",
        climate="subtropical",
        origin="Caraïbes",
        photosynthesis="C3",
        edible_part="fruit",
    ),
    Species(
        common="Limettier",
        latin="Citrus aurantiifolia",
        family="Rutaceae",
        category="Agrume",
        product="hespérides aromatiques",
        climate="tropical humide",
        origin="Asie du Sud-Est",
        photosynthesis="C3",
        edible_part="fruit",
    ),
    Species(
        common="Mandarinier",
        latin="Citrus reticulata",
        family="Rutaceae",
        category="Agrume",
        product="hespérides faciles à peler",
        climate="subtropical",
        origin="Asie orientale",
        photosynthesis="C3",
        edible_part="fruit",
    ),
    Species(
        common="Kiwi",
        latin="Actinidia deliciosa",
        family="Actinidiaceae",
        category="Fruit climactérique",
        product="baies velues",
        climate="tempéré humide",
        origin="Chine méridionale",
        photosynthesis="C3",
        edible_part="fruit",
    ),
    Species(
        common="Figuier",
        latin="Ficus carica",
        family="Moraceae",
        category="Arbre fruitier méditerranéen",
        product="sycones sucrés",
        climate="méditerranéen",
        origin="Méditerranée orientale",
        photosynthesis="C3",
        edible_part="fruit",
    ),
    Species(
        common="Grenadier",
        latin="Punica granatum",
        family="Lythraceae",
        category="Arbre fruitier méditerranéen",
        product="baies à arilles",
        climate="méditerranéen",
        origin="Iran occidental",
        photosynthesis="C3",
        edible_part="fruit",
    ),
    Species(
        common="Noisetier",
        latin="Corylus avellana",
        family="Betulaceae",
        category="Noix tempérée",
        product="noisettes oléagineuses",
        climate="tempéré",
        origin="Europe orientale",
        photosynthesis="C3",
        edible_part="graine",
    ),
    Species(
        common="Noyer",
        latin="Juglans regia",
        family="Juglandaceae",
        category="Noix tempérée",
        product="noix oléagineuses",
        climate="tempéré",
        origin="Asie centrale",
        photosynthesis="C3",
        edible_part="graine",
    ),
    Species(
        common="Amandier",
        latin="Prunus dulcis",
        family="Rosaceae",
        category="Noix méditerranéenne",
        product="amandes oléagineuses",
        climate="méditerranéen",
        origin="Méditerranée orientale",
        photosynthesis="C3",
        edible_part="graine",
    ),
    Species(
        common="Pistachier",
        latin="Pistacia vera",
        family="Anacardiaceae",
        category="Noix méditerranéenne",
        product="graines vertes",
        climate="aride tempéré",
        origin="Asie occidentale",
        photosynthesis="C3",
        edible_part="graine",
    ),
    Species(
        common="Anacardier",
        latin="Anacardium occidentale",
        family="Anacardiaceae",
        category="Noix tropicale",
        product="noix de cajou",
        climate="tropical sec",
        origin="Nord-Est du Brésil",
        photosynthesis="C3",
        edible_part="graine",
    ),
    Species(
        common="Châtaignier",
        latin="Castanea sativa",
        family="Fagaceae",
        category="Noix tempérée",
        product="akènes féculents",
        climate="tempéré humide",
        origin="Asie Mineure",
        photosynthesis="C3",
        edible_part="graine",
    ),
    Species(
        common="Noyer de macadamia",
        latin="Macadamia integrifolia",
        family="Proteaceae",
        category="Noix tropicale",
        product="noix riches en huile",
        climate="subtropical",
        origin="Australie orientale",
        photosynthesis="C3",
        edible_part="graine",
    ),
    Species(
        common="Colza",
        latin="Brassica napus",
        family="Brassicaceae",
        category="Plante oléagineuse",
        product="graines pour huile",
        climate="tempéré",
        origin="Europe du Nord",
        photosynthesis="C3",
        edible_part="graine",
    ),
    Species(
        common="Tournesol",
        latin="Helianthus annuus",
        family="Asteraceae",
        category="Plante oléagineuse",
        product="akènes oléagineux",
        climate="tempéré chaud",
        origin="Grandes Plaines nord-américaines",
        photosynthesis="C3",
        edible_part="graine",
    ),
    Species(
        common="Lin cultivé",
        latin="Linum usitatissimum",
        family="Linaceae",
        category="Plante oléagineuse",
        product="graines et fibres",
        climate="tempéré frais",
        origin="Croissant fertile",
        photosynthesis="C3",
        edible_part="graine",
    ),
    Species(
        common="Sésame",
        latin="Sesamum indicum",
        family="Pedaliaceae",
        category="Plante oléagineuse",
        product="graines riches en huile",
        climate="tropical sec",
        origin="Inde",
        photosynthesis="C3",
        edible_part="graine",
    ),
    Species(
        common="Ricin",
        latin="Ricinus communis",
        family="Euphorbiaceae",
        category="Plante oléagineuse",
        product="huile industrielle",
        climate="tropical",
        origin="Afrique de l'Est",
        photosynthesis="C3",
        edible_part=None,
    ),
    Species(
        common="Chanvre",
        latin="Cannabis sativa",
        family="Cannabaceae",
        category="Plante à fibre",
        product="fibres textiles et chènevis",
        climate="tempéré",
        origin="Asie centrale",
        photosynthesis="C3",
        edible_part="graine",
    ),
    Species(
        common="Coton",
        latin="Gossypium hirsutum",
        family="Malvaceae",
        category="Plante à fibre",
        product="fibres textiles",
        climate="tropical",
        origin="Amérique centrale",
        photosynthesis="C3",
        edible_part=None,
    ),
    Species(
        common="Jute",
        latin="Corchorus olitorius",
        family="Malvaceae",
        category="Plante à fibre",
        product="fibres pour sacs",
        climate="tropical humide",
        origin="Bengale",
        photosynthesis="C3",
        edible_part="feuille",
    ),
    Species(
        common="Sisal",
        latin="Agave sisalana",
        family="Asparagaceae",
        category="Plante à fibre",
        product="fibres de feuilles",
        climate="tropical sec",
        origin="Mexique méridional",
        photosynthesis="CAM",
        edible_part=None,
    ),
    Species(
        common="Ramie",
        latin="Boehmeria nivea",
        family="Urticaceae",
        category="Plante à fibre",
        product="fibres fines",
        climate="subtropical humide",
        origin="Chine méridionale",
        photosynthesis="C3",
        edible_part=None,
    ),
    Species(
        common="Agave bleu",
        latin="Agave tequilana",
        family="Asparagaceae",
        category="Plante sucrière",
        product="cœur riche en inuline",
        climate="tropical sec",
        origin="Mexique occidental",
        photosynthesis="CAM",
        edible_part="tige",
    ),
    Species(
        common="Aloe vera",
        latin="Aloe vera",
        family="Asphodelaceae",
        category="Plante médicinale",
        product="gel mucilagineux",
        climate="subtropical sec",
        origin="Péninsule arabique",
        photosynthesis="CAM",
        edible_part="feuille",
    ),
    Species(
        common="Opuntia",
        latin="Opuntia ficus-indica",
        family="Cactaceae",
        category="Fruit cactus",
        product="raquettes et fruits",
        climate="aride",
        origin="Mexique",
        photosynthesis="CAM",
        edible_part="tige",
    ),
    Species(
        common="Vanille",
        latin="Vanilla planifolia",
        family="Orchidaceae",
        category="Plante à épice",
        product="gousses aromatiques",
        climate="tropical humide",
        origin="Mexique",
        photosynthesis="C3",
        edible_part="fruit",
    ),
    Species(
        common="Safran",
        latin="Crocus sativus",
        family="Iridaceae",
        category="Plante à épice",
        product="stigmates séchés",
        climate="méditerranéen",
        origin="Méditerranée orientale",
        photosynthesis="C3",
        edible_part="stigmate",
    ),
    Species(
        common="Cannelle",
        latin="Cinnamomum verum",
        family="Lauraceae",
        category="Plante à épice",
        product="écorce aromatique",
        climate="tropical humide",
        origin="Sri Lanka",
        photosynthesis="C3",
        edible_part="écorce",
    ),
    Species(
        common="Clou de girofle",
        latin="Syzygium aromaticum",
        family="Myrtaceae",
        category="Plante à épice",
        product="boutons floraux",
        climate="tropical humide",
        origin="Îles Moluques",
        photosynthesis="C3",
        edible_part="bouton floral",
    ),
    Species(
        common="Poivre noir",
        latin="Piper nigrum",
        family="Piperaceae",
        category="Plante à épice",
        product="drupes séchées",
        climate="tropical humide",
        origin="Inde du Sud-Ouest",
        photosynthesis="C3",
        edible_part="fruit",
    ),
    Species(
        common="Gingembre",
        latin="Zingiber officinale",
        family="Zingiberaceae",
        category="Plante à épice",
        product="rhizomes aromatiques",
        climate="tropical humide",
        origin="Asie du Sud-Est",
        photosynthesis="C3",
        edible_part="rhizome",
    ),
    Species(
        common="Curcuma",
        latin="Curcuma longa",
        family="Zingiberaceae",
        category="Plante à épice",
        product="rhizomes orangés",
        climate="tropical humide",
        origin="Inde du Sud",
        photosynthesis="C3",
        edible_part="rhizome",
    ),
    Species(
        common="Cardamome verte",
        latin="Elettaria cardamomum",
        family="Zingiberaceae",
        category="Plante à épice",
        product="capsules aromatiques",
        climate="tropical humide",
        origin="Ghats occidentaux",
        photosynthesis="C3",
        edible_part="fruit",
    ),
    Species(
        common="Muscadier",
        latin="Myristica fragrans",
        family="Myristicaceae",
        category="Plante à épice",
        product="graines aromatiques",
        climate="tropical humide",
        origin="Îles Banda",
        photosynthesis="C3",
        edible_part="graine",
    ),
    Species(
        common="Piment oiseau",
        latin="Capsicum frutescens",
        family="Solanaceae",
        category="Plante à épice",
        product="fruits piquants",
        climate="tropical humide",
        origin="Amérique tropicale",
        photosynthesis="C3",
        edible_part="fruit",
    ),
    Species(
        common="Paprika",
        latin="Capsicum annuum var. longum",
        family="Solanaceae",
        category="Plante à épice",
        product="fruits séchés",
        climate="tempéré chaud",
        origin="Mexique",
        photosynthesis="C3",
        edible_part="fruit",
    ),
    Species(
        common="Basilic",
        latin="Ocimum basilicum",
        family="Lamiaceae",
        category="Plante aromatique",
        product="feuilles aromatiques",
        climate="méditerranéen",
        origin="Asie du Sud",
        photosynthesis="C3",
        edible_part="feuille",
    ),
    Species(
        common="Thym",
        latin="Thymus vulgaris",
        family="Lamiaceae",
        category="Plante aromatique",
        product="feuilles riches en thymol",
        climate="méditerranéen",
        origin="Bassin méditerranéen",
        photosynthesis="C3",
        edible_part="feuille",
    ),
    Species(
        common="Romarin",
        latin="Salvia rosmarinus",
        family="Lamiaceae",
        category="Plante aromatique",
        product="feuilles camphrées",
        climate="méditerranéen",
        origin="Bassin méditerranéen",
        photosynthesis="C3",
        edible_part="feuille",
    ),
    Species(
        common="Laurier-sauce",
        latin="Laurus nobilis",
        family="Lauraceae",
        category="Plante aromatique",
        product="feuilles coriaces",
        climate="méditerranéen",
        origin="Méditerranée orientale",
        photosynthesis="C3",
        edible_part="feuille",
    ),
    Species(
        common="Menthe poivrée",
        latin="Mentha × piperita",
        family="Lamiaceae",
        category="Plante aromatique",
        product="feuilles mentholées",
        climate="tempéré humide",
        origin="Europe",
        photosynthesis="C3",
        edible_part="feuille",
    ),
    Species(
        common="Ciboulette",
        latin="Allium schoenoprasum",
        family="Amaryllidaceae",
        category="Plante aromatique",
        product="feuilles tubulaires",
        climate="tempéré",
        origin="Europe septentrionale",
        photosynthesis="C3",
        edible_part="feuille",
    ),
    Species(
        common="Coriandre",
        latin="Coriandrum sativum",
        family="Apiaceae",
        category="Plante aromatique",
        product="feuilles et graines",
        climate="méditerranéen",
        origin="Bassin méditerranéen",
        photosynthesis="C3",
        edible_part="feuille",
    ),
    Species(
        common="Persil",
        latin="Petroselinum crispum",
        family="Apiaceae",
        category="Plante aromatique",
        product="feuilles fraîches",
        climate="tempéré",
        origin="Méditerranée",
        photosynthesis="C3",
        edible_part="feuille",
    ),
    Species(
        common="Aneth",
        latin="Anethum graveolens",
        family="Apiaceae",
        category="Plante aromatique",
        product="feuilles et graines",
        climate="tempéré",
        origin="Europe orientale",
        photosynthesis="C3",
        edible_part="feuille",
    ),
    Species(
        common="Fenouil doux",
        latin="Foeniculum vulgare",
        family="Apiaceae",
        category="Plante aromatique",
        product="bulbes anisés",
        climate="méditerranéen",
        origin="Méditerranée",
        photosynthesis="C3",
        edible_part="bulbe",
    ),
    Species(
        common="Estragon",
        latin="Artemisia dracunculus",
        family="Asteraceae",
        category="Plante aromatique",
        product="feuilles anisées",
        climate="tempéré sec",
        origin="Sibérie méridionale",
        photosynthesis="C3",
        edible_part="feuille",
    ),
    Species(
        common="Sauge officinale",
        latin="Salvia officinalis",
        family="Lamiaceae",
        category="Plante aromatique",
        product="feuilles aromatiques",
        climate="méditerranéen",
        origin="Bassin méditerranéen",
        photosynthesis="C3",
        edible_part="feuille",
    ),
    Species(
        common="Camomille matricaire",
        latin="Matricaria chamomilla",
        family="Asteraceae",
        category="Plante médicinale",
        product="capitules pour infusion",
        climate="tempéré",
        origin="Europe orientale",
        photosynthesis="C3",
        edible_part="fleur",
    ),
    Species(
        common="Lavande vraie",
        latin="Lavandula angustifolia",
        family="Lamiaceae",
        category="Plante aromatique",
        product="fleurs parfumées",
        climate="méditerranéen",
        origin="Provence",
        photosynthesis="C3",
        edible_part="fleur",
    ),
    Species(
        common="Origan",
        latin="Origanum vulgare",
        family="Lamiaceae",
        category="Plante aromatique",
        product="feuilles méditerranéennes",
        climate="méditerranéen",
        origin="Bassin méditerranéen",
        photosynthesis="C3",
        edible_part="feuille",
    ),
    Species(
        common="Sarriette",
        latin="Satureja hortensis",
        family="Lamiaceae",
        category="Plante aromatique",
        product="feuilles poivrées",
        climate="tempéré sec",
        origin="Europe du Sud",
        photosynthesis="C3",
        edible_part="feuille",
    ),
    Species(
        common="Cerfeuil",
        latin="Anthriscus cerefolium",
        family="Apiaceae",
        category="Plante aromatique",
        product="feuilles délicates",
        climate="tempéré frais",
        origin="Europe orientale",
        photosynthesis="C3",
        edible_part="feuille",
    ),
    Species(
        common="Marjolaine",
        latin="Origanum majorana",
        family="Lamiaceae",
        category="Plante aromatique",
        product="feuilles douces",
        climate="tempéré sec",
        origin="Méditerranée orientale",
        photosynthesis="C3",
        edible_part="feuille",
    ),
    Species(
        common="Stevia",
        latin="Stevia rebaudiana",
        family="Asteraceae",
        category="Plante édulcorante",
        product="feuilles riches en stéviosides",
        climate="subtropical",
        origin="Paraguay",
        photosynthesis="C3",
        edible_part="feuille",
    ),
    Species(
        common="Rooibos",
        latin="Aspalathus linearis",
        family="Fabaceae",
        category="Plante pour infusion",
        product="rameaux fermentés",
        climate="semi-aride",
        origin="Afrique du Sud",
        photosynthesis="C3",
        edible_part="feuille",
    ),
]

# Limiter volontairement la base variétale à 120 espèces pour calibrer le volume final de questions.
SPECIES_DATA = SPECIES_DATA[:120]


def sample_distractors(pool: Sequence[str], correct: str, k: int) -> List[str]:
    options = [item for item in pool if item != correct]
    if len(options) < k:
        raise ValueError(f"Not enough distractors to sample {k} unique options from {len(set(pool))} items")
    return RNG.sample(options, k)


def build_choices(correct: str, wrong: Iterable[str]) -> List[dict]:
    options = [correct, *wrong]
    RNG.shuffle(options)
    choices = []
    for idx, text in enumerate(options):
        entry = {"id": chr(ord("a") + idx), "text": text}
        if text == correct:
            entry["correct"] = True
        choices.append(entry)
    return choices


LEVEL_COUNTERS = {level: 1 for level in range(1, 13)}
QUESTIONS: List[dict] = []


def add_question(level: int, prompt: str, correct: str, wrong: Sequence[str], explanation: str) -> None:
    question_id = f"L{level:02d}Q{LEVEL_COUNTERS[level]:03d}"
    LEVEL_COUNTERS[level] += 1
    QUESTIONS.append(
        {
            "id": question_id,
            "level": level,
            "prompt": prompt,
            "choices": build_choices(correct, wrong),
            "explanation": explanation,
        }
    )


# Build helper pools for species-derived questions.
CATEGORIES = sorted({species.category for species in SPECIES_DATA})
PRODUCTS = sorted({species.product for species in SPECIES_DATA})
ORIGINS = sorted({species.origin for species in SPECIES_DATA})
FAMILIES = sorted({species.family for species in SPECIES_DATA})
COMMON_NAMES = [species.common for species in SPECIES_DATA]
LATIN_NAMES = [species.latin for species in SPECIES_DATA]
EDIBLE_PARTS = sorted({species.edible_part for species in SPECIES_DATA if species.edible_part})

PHOTOSYNTHESIS_CHOICES = ["C3", "C4", "CAM", "C3-CAM facultatif"]


for species in SPECIES_DATA:
    # Level 1: category recognition
    add_question(
        level=1,
        prompt=f"Dans quelle grande catégorie de cultures classe-t-on le/la {species.common} ?",
        correct=species.category,
        wrong=sample_distractors(CATEGORIES, species.category, 3),
        explanation=f"Le/la {species.common} est classé(e) comme {species.category} en raison de son utilisation principale.",
    )

    # Level 2: principal product
    add_question(
        level=2,
        prompt=f"Quel produit principal obtient-on de la culture du/de la {species.common} ?",
        correct=species.product,
        wrong=sample_distractors(PRODUCTS, species.product, 3),
        explanation=f"Le produit recherché du/de la {species.common} est {species.product}.",
    )

    # Level 3: edible or valorised organ when available
    if species.edible_part:
        add_question(
            level=3,
            prompt=f"Quelle partie du/de la {species.common} est habituellement consommée ou valorisée en alimentation ?",
            correct=species.edible_part,
            wrong=sample_distractors(EDIBLE_PARTS, species.edible_part, 3),
            explanation=f"Chez le/la {species.common}, c'est principalement la/le {species.edible_part} qui est utilisé(e) en cuisine.",
        )
    else:
        add_question(
            level=3,
            prompt=f"Quel type de valorisation privilégie-t-on pour le/la {species.common} ?",
            correct=species.product,
            wrong=sample_distractors(PRODUCTS, species.product, 3),
            explanation=f"Le/de la {species.common} est cultivé(e) surtout pour {species.product}.",
        )

    # Level 4: common name to scientific name
    add_question(
        level=4,
        prompt=f"Quel est le nom scientifique du/de la {species.common} ?",
        correct=species.latin,
        wrong=sample_distractors(LATIN_NAMES, species.latin, 3),
        explanation=f"Le nom scientifique du/de la {species.common} est {species.latin}.",
    )

    # Level 4: scientific name to common name
    add_question(
        level=4,
        prompt=f"Quel nom commun correspond à {species.latin} ?",
        correct=species.common,
        wrong=sample_distractors(COMMON_NAMES, species.common, 3),
        explanation=f"{species.latin} est le nom scientifique du/de la {species.common}.",
    )

    # Level 5: geographic origin
    add_question(
        level=5,
        prompt=f"Quelle région d'origine est associée à la domestication du/de la {species.common} ?",
        correct=species.origin,
        wrong=sample_distractors(ORIGINS, species.origin, 3),
        explanation=f"Le/la {species.common} a été domestiqué(e) à l'origine dans la région {species.origin}.",
    )

    # Level 6: botanical family
    add_question(
        level=6,
        prompt=f"À quelle famille botanique appartient le/la {species.common} ?",
        correct=species.family,
        wrong=sample_distractors(FAMILIES, species.family, 3),
        explanation=f"Le/la {species.common} fait partie de la famille des {species.family}.",
    )

    # Level 7: photosynthesis type
    wrong_photo = [opt for opt in PHOTOSYNTHESIS_CHOICES if opt != species.photosynthesis]
    RNG.shuffle(wrong_photo)
    add_question(
        level=7,
        prompt=f"Quel type de photosynthèse caractérise principalement le/la {species.common} ?",
        correct=species.photosynthesis,
        wrong=wrong_photo[:3],
        explanation=f"Le/la {species.common} fonctionne essentiellement en mode de photosynthèse {species.photosynthesis}.",
    )

ADVANCED_QUESTIONS = [
    {
        "level": 8,
        "prompt": "Quelle hormone végétale déclenche l'allongement cellulaire dans les tiges et favorise la dominance apicale ?",
        "correct": "Auxine (IAA)",
        "wrong": ["Gibbérelline", "Cytokinine", "Acide abscissique"],
        "explanation": "Les auxines, principalement l'IAA, stimulent l'allongement cellulaire et maintiennent la dominance apicale des tiges.",
    },
    {
        "level": 8,
        "prompt": "Quelle famille d'hormones végétales stimule la division cellulaire dans les méristèmes ?",
        "correct": "Cytokinines",
        "wrong": ["Jasmonates", "Brassinostéroïdes", "Strigolactones"],
        "explanation": "Les cytokinines sont impliquées dans la stimulation des divisions cellulaires et le maintien des méristèmes.",
    },
    {
        "level": 8,
        "prompt": "Quel signal hormonal favorise la levée de dormance des graines et l'allongement des entre-nœuds ?",
        "correct": "Gibbérellines",
        "wrong": ["Acide salicylique", "Ethylène", "Auxines"],
        "explanation": "Les gibbérellines déclenchent la synthèse d'enzymes mobilisant les réserves, levant la dormance des graines et favorisant l'élongation des tiges.",
    },
    {
        "level": 8,
        "prompt": "Quel messager déclenche la fermeture rapide des stomates en situation de stress hydrique ?",
        "correct": "Acide abscissique",
        "wrong": ["Ethylène", "Cytokinine", "Brassinostéroïde"],
        "explanation": "L'acide abscissique accumulé dans les feuilles signale la fermeture stomatique pour limiter la transpiration.",
    },
    {
        "level": 8,
        "prompt": "Quelle hormone gazeuse accélère la maturation des fruits climactériques ?",
        "correct": "Ethylène",
        "wrong": ["Jasmonate", "Acide abscissique", "Strigolactone"],
        "explanation": "L'ethylène est un gaz produit par les fruits climactériques qui synchronise la maturation.",
    },
    {
        "level": 8,
        "prompt": "Quel messager végétal limite la ramification latérale et coordonne la symbiose mycorhizienne ?",
        "correct": "Strigolactones",
        "wrong": ["Brassinostéroïdes", "Acide salicylique", "Polyamines"],
        "explanation": "Les strigolactones régulent l'architecture de la plante et servent de signal d'attraction pour certains champignons symbiotiques.",
    },
    {
        "level": 8,
        "prompt": "Quel groupe d'hormones végétales renforce les parois et participe à la tolérance au stress mécanique ?",
        "correct": "Brassinostéroïdes",
        "wrong": ["Auxines", "Cytokinines", "Jasmonates"],
        "explanation": "Les brassinostéroïdes modulent l'élasticité de la paroi cellulaire et améliorent la résistance mécanique des organes.",
    },
    {
        "level": 8,
        "prompt": "Quel signal lipidique est surtout associé aux réponses de défense contre les herbivores ?",
        "correct": "Jasmonates",
        "wrong": ["Acide abscissique", "Cytokinines", "Ethylène"],
        "explanation": "Les jasmonates déclenchent des cascades de défense, notamment la production de composés anti-herbivores.",
    },
    {
        "level": 9,
        "prompt": "Où se déroule la phase photochimique (lumineuse) de la photosynthèse ?",
        "correct": "Dans les thylakoïdes des chloroplastes",
        "wrong": ["Dans le stroma mitochondrial", "Dans le cytosol", "Dans les vacuoles"],
        "explanation": "Les photosystèmes I et II ainsi que la chaîne de transport d'électrons sont localisés dans les membranes thylakoïdiennes.",
    },
    {
        "level": 9,
        "prompt": "Quel enzyme fixe le CO₂ dans le cycle de Calvin-Benson ?",
        "correct": "Rubisco",
        "wrong": ["PEP carboxylase", "Nitrate réductase", "ATP synthase"],
        "explanation": "La rubisco catalyse la carboxylation du ribulose-1,5-bisphosphate lors de la phase sombre de la photosynthèse.",
    },
    {
        "level": 9,
        "prompt": "Quel organite participe à la photorespiration avec le chloroplaste et la mitochondrie ?",
        "correct": "Le peroxysome",
        "wrong": ["Le noyau", "Le réticulum endoplasmique", "La vacuole"],
        "explanation": "La photorespiration implique une navette métabolique entre chloroplastes, peroxysomes et mitochondries.",
    },
    {
        "level": 9,
        "prompt": "Quel composé est principalement transporté dans le phloème des angiospermes ?",
        "correct": "Saccharose",
        "wrong": ["Glucose libre", "Amidon", "Malate"],
        "explanation": "Le saccharose est la forme dominante de transport des assimilats carbonés dans le phloème.",
    },
    {
        "level": 9,
        "prompt": "Quel cofacteur réduit fournit les électrons à la chaîne photosynthétique lors du cycle de Calvin ?",
        "correct": "NADPH",
        "wrong": ["FADH₂", "NADH", "FMNH₂"],
        "explanation": "Le NADPH généré par la phase lumineuse est consommé dans le stroma pour réduire le 3-phosphoglycérate.",
    },
    {
        "level": 9,
        "prompt": "Quelle est la ploidie de l'endosperme des angiospermes après double fécondation ?",
        "correct": "Triploïde (3n)",
        "wrong": ["Diploïde (2n)", "Haploïde (n)", "Hexaploïde (6n)"],
        "explanation": "La double fécondation fusionne un noyau spermatique avec les deux noyaux polaires, formant un tissu triploïde.",
    },
    {
        "level": 9,
        "prompt": "Quel ion est le principal moteur du chargement phloémien via les symporteurs de sucres ?",
        "correct": "Le proton H⁺",
        "wrong": ["Le sodium Na⁺", "Le potassium K⁺", "Le calcium Ca²⁺"],
        "explanation": "Le gradient électrochimique de protons créé par les H⁺-ATPases fournit l'énergie pour les symporteurs de saccharose.",
    },
    {
        "level": 9,
        "prompt": "Quelle molécule sert d'accepteur final d'électrons dans la chaîne photosynthétique du photosystème I ?",
        "correct": "La ferrédoxine",
        "wrong": ["Le cytochrome c", "La plastocyanine", "L'ubiquinone"],
        "explanation": "La ferrédoxine reçoit les électrons réduits du photosystème I avant de réduire le NADP⁺.",
    },
    {
        "level": 10,
        "prompt": "Quel type de sélection repose sur l'introgression de gènes de résistance issus d'espèces sauvages apparentées ?",
        "correct": "Pré-breeding (pré-amélioration)",
        "wrong": ["Sélection massale", "Sélection récurrente réciproque", "Culture in vitro"],
        "explanation": "Le pré-breeding intègre des allèles d'intérêt provenant de ressources sauvages dans des fonds génétiques cultivés.",
    },
    {
        "level": 10,
        "prompt": "Quelle technique permet de cartographier rapidement des QTL grâce à des marqueurs SNP denses ?",
        "correct": "Génomique d'association (GWAS)",
        "wrong": ["PCR conventionnelle", "Hybridation Southern", "Isoélectrofocalisation"],
        "explanation": "Les études d'association à l'échelle du génome exploitent de nombreux SNP pour relier phénotype et génotype.",
    },
    {
        "level": 10,
        "prompt": "Quel agent pathogène est responsable du mildiou de la vigne en Europe ?",
        "correct": "Plasmopara viticola",
        "wrong": ["Phytophthora infestans", "Puccinia graminis", "Botrytis cinerea"],
        "explanation": "Plasmopara viticola, un oomycète, provoque le mildiou de la vigne introduit depuis l'Amérique au XIXᵉ siècle.",
    },
    {
        "level": 10,
        "prompt": "Quel virus est contrôlé par l'introduction du gène papaya ringspot resistance à Hawaï ?",
        "correct": "Potyvirus PRSV",
        "wrong": ["Tomato mosaic virus", "Cucumber mosaic virus", "Banana bunchy top virus"],
        "explanation": "La papaye transgénique Rainbow contient un gène de capside conférant une résistance au Papaya ringspot virus (PRSV).",
    },
    {
        "level": 10,
        "prompt": "Quelle toxine bactérienne de Bacillus thuringiensis cible les lépidoptères ravageurs du maïs ?",
        "correct": "Cry1Ab",
        "wrong": ["Vip3A", "Cry3Bb", "Cry34Ab"],
        "explanation": "La protéine Cry1Ab insérée dans certains maïs Bt contrôle surtout les larves de pyrales et sésamies (Lepidoptera).",
    },
    {
        "level": 10,
        "prompt": "Quel champignon provoque la rouille orangée du blé nécessitant des variétés résistantes à la race Ug99 ?",
        "correct": "Puccinia graminis f. sp. tritici",
        "wrong": ["Puccinia striiformis", "Puccinia recondita", "Ustilago maydis"],
        "explanation": "La rouille noire du blé due à Puccinia graminis f. sp. tritici possède une lignée très virulente appelée Ug99.",
    },
    {
        "level": 10,
        "prompt": "Quel mécanisme génétique sous-tend la stérilité mâle cytoplasmique utilisée en production d'hybrides ?",
        "correct": "Interaction gènes mitochondriaux / gènes restaurateurs nucléaires",
        "wrong": ["Mutation chloroplastique dominante", "Polyploïdisation spontanée", "Transposon actif dans le noyau"],
        "explanation": "La stérilité mâle cytoplasmique résulte d'altérations mitochondrial es compensées par des gènes restaurateurs nucléaires.",
    },
    {
        "level": 10,
        "prompt": "Quel outil permet de modifier précisément un gène végétal via un ARN guide et une nucléase ?",
        "correct": "CRISPR-Cas9",
        "wrong": ["Zinc finger nuclease", "Méthylation ciblée", "Électroporation"],
        "explanation": "Le système CRISPR-Cas9 utilise un ARN guide pour cibler spécifiquement une séquence génomique et induire une coupure contrôlée.",
    },
    {
        "level": 11,
        "prompt": "Quel type de symbiose unit des champignons à arbuscules et les racines de la majorité des plantes cultivées ?",
        "correct": "Mycorhize endomycorhizienne (AMF)",
        "wrong": ["Mycorhize ectomycorhizienne", "Rhizobiose nodulaire", "Lichenisation"],
        "explanation": "Les champignons mycorhiziens à arbuscules colonisent les racines et améliorent l'acquisition de phosphore chez de nombreuses cultures.",
    },
    {
        "level": 11,
        "prompt": "Quel type de fixation symbiotique de l'azote domine chez les Fabaceae tropicales ?",
        "correct": "Symbiose avec des rhizobia du genre Bradyrhizobium",
        "wrong": ["Association Frankia", "Fixation libre par Azotobacter", "Symbiose avec Nostoc"],
        "explanation": "Les légumineuses tropicales hébergent fréquemment des Bradyrhizobium adaptés aux températures élevées.",
    },
    {
        "level": 11,
        "prompt": "Quel terme décrit une plante adaptée aux milieux salins par accumulation de sels dans ses vacuoles ?",
        "correct": "Halophyte",
        "wrong": ["Xérophyte", "Hydrophyte", "Calcicole"],
        "explanation": "Les halophytes tolèrent des teneurs élevées en sel grâce à la compartimentation vacuolaire et à la succulence.",
    },
    {
        "level": 11,
        "prompt": "Quelle stratégie d'évitement de la sécheresse consiste à compléter le cycle de vie avant la saison sèche ?",
        "correct": "Évasion phénologique",
        "wrong": ["Tolérance osmotique", "Succulence", "Dormance des bourgeons"],
        "explanation": "Les plantes à évitation phénologique synchronisent leur reproduction avant les périodes défavorables.",
    },
    {
        "level": 11,
        "prompt": "Quel biome est dominé par des graminées C4 tolérantes au feu et des sols profonds bien drainés ?",
        "correct": "Savane tropicale",
        "wrong": ["Steppe froide", "Forêt boréale", "Maquis méditerranéen"],
        "explanation": "Les savanes tropicales associent herbacées C4 et arbres clairsemés, entretenus par le feu et le pâturage.",
    },
    {
        "level": 11,
        "prompt": "Quel processus décrit le transfert d'auxines depuis une feuille ombragée pour favoriser son orientation vers la lumière ?",
        "correct": "Phototropisme",
        "wrong": ["Gravitropisme", "Thigmotropisme", "Hydrotropisme"],
        "explanation": "Le phototropisme implique une redistribution d'auxine vers le côté ombré, induisant une courbure vers la lumière.",
    },
    {
        "level": 11,
        "prompt": "Quel terme désigne les composés chimiques émis pour inhiber la germination des plantes concurrentes ?",
        "correct": "Allélopathie",
        "wrong": ["Commensalisme", "Mutualisme", "Parasitisme"],
        "explanation": "L'allélopathie correspond à l'émission de molécules inhibitrices par certaines plantes pour limiter leurs compétitrices.",
    },
    {
        "level": 11,
        "prompt": "Quelle adaptation racinaire améliore l'accès au phosphore dans les sols pauvres des Proteaceae ?",
        "correct": "Racines en grappes (cluster roots)",
        "wrong": ["Racines aériennes", "Rhizomes traçants", "Pneumatophores"],
        "explanation": "Les racines en grappes exsudent des acides organiques mobilisant le phosphore insoluble.",
    },
    {
        "level": 12,
        "prompt": "Quelle technique de séquençage mesure simultanément l'abondance des transcrits dans un tissu végétal ?",
        "correct": "RNA-seq",
        "wrong": ["ChIP-seq", "ATAC-seq", "Bisulfite-seq"],
        "explanation": "La RNA-seq quantifie l'expression génique en séquençant les ARN messagers convertis en cDNA.",
    },
    {
        "level": 12,
        "prompt": "Quel outil de phénotypage haut débit utilise l'imagerie hyperspectrale pour surveiller l'état hydrique ?",
        "correct": "Plateforme phénotypique proximal hyperspectrale",
        "wrong": ["PCR en temps réel", "Chromatographie HPLC", "Dosage Kjeldahl"],
        "explanation": "Les plateformes hyperspectrales détectent précocement le stress hydrique via des signatures optiques fines.",
    },
    {
        "level": 12,
        "prompt": "Quel type de modèle relie données climatiques et réponse culturale pour projeter les rendements futurs ?",
        "correct": "Modèle agroclimatique mécaniste",
        "wrong": ["Modèle ARIMA", "Analyse en composantes principales", "Diagramme de Voronoï"],
        "explanation": "Les modèles agroclimatiques mécanistes simulent la croissance en fonction des flux d'énergie et d'eau.",
    },
    {
        "level": 12,
        "prompt": "Quelle technique permet de profiler la chromatine accessible dans les noyaux végétaux ?",
        "correct": "ATAC-seq",
        "wrong": ["RNA-seq", "DGE", "SDS-PAGE"],
        "explanation": "ATAC-seq (Assay for Transposase-Accessible Chromatin) cartographie les régions de chromatine ouverte.",
    },
    {
        "level": 12,
        "prompt": "Quel outil robotisé automatise les croisements contrôlés en sélection accélérée ?",
        "correct": "Chambre de speed breeding",
        "wrong": ["Fermenteur à biomasse", "Spectromètre de masse", "Microscope confocal"],
        "explanation": "Le speed breeding combine éclairage LED et contrôle climatique pour raccourcir les cycles de reproduction.",
    },
    {
        "level": 12,
        "prompt": "Quel concept désigne l'intégration de données génomiques, phénotypiques et environnementales par IA pour la sélection ?",
        "correct": "Phénotypage génomique assisté par IA",
        "wrong": ["Mutagénèse aléatoire", "Culture hydroponique", "Compostage de précision"],
        "explanation": "L'IA croise des jeux de données multi-sources afin de prédire les performances variétales dans divers scénarios.",
    },
    {
        "level": 12,
        "prompt": "Quel marqueur moléculaire bi-allelique est massivement utilisé dans les programmes de sélection assistée ?",
        "correct": "SNP (Single Nucleotide Polymorphism)",
        "wrong": ["RFLP", "RAPD", "AFLP"],
        "explanation": "Les SNP offrent une densité élevée et sont aisément génotypables pour la sélection assistée par marqueurs.",
    },
    {
        "level": 12,
        "prompt": "Quelle approche statistique prédit la valeur génétique des individus à partir d'un grand nombre de marqueurs ?",
        "correct": "Sélection génomique (GBLUP)",
        "wrong": ["Analyse discriminante", "Réseau de neurones convolutionnel", "Test de Student"],
        "explanation": "La sélection génomique utilise des modèles GBLUP ou bayésiens pour estimer la valeur génétique à partir des marqueurs.",
    },
]


for item in ADVANCED_QUESTIONS:
    add_question(
        level=item["level"],
        prompt=item["prompt"],
        correct=item["correct"],
        wrong=item["wrong"],
        explanation=item["explanation"],
    )


QUESTIONS.sort(key=lambda q: (q["level"], q["id"]))

with DATA_PATH.open("w", encoding="utf-8") as f:
    json.dump(QUESTIONS, f, ensure_ascii=False, indent=2)
    f.write("\n")


if __name__ == "__main__":
    print(f"Generated {len(QUESTIONS)} questions in {DATA_PATH}")
